(define (problem task5)
   (:domain secrets)
   (:objects a1 a2 a3 a4 a5 a6 - agent s1 s2 - secret)
   (:init 
      (connect a1 a2)
      (connect a1 a3)
      (connect a2 a4)
      (connect a3 a5)
      (connect a3 a6)
      (connect a4 a5)
      (connect a5 a3)
      (deceptive a5)
      (agentTrueBelif a1 s1)
   )
   (:goal 
      (and
         (agentFalseBelif a3 s1) 
         (agentTrueBelif a6 s1)
      )
   )
)
